board/urls.py
from django.urls import path

from . import views

app_name = 'board'


urlpatterns = [
    path('', views.index, name='index'),
    path('list/', views.list, name='list'),
    path('read/<int:id>/', views.read, name='read'),
    path('regist/', views.regist, name='regist'),
    path('edit/<int:id>/', views.edit, name='edit'),
    path('remove/<int:id>/', views.edit, name='edit'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
]

board/models.py
from django.db import models

from django.utils import timezone

class Board(models.Model):
    title = models.CharField(max_length=50)
    writer = models.CharField(max_length=30)
    content = models.TextField()
    regdate = models.DateTimeField(auto_now=timezone.now)
    readcount = models.IntegerField(default=0)


    def __str__(self):
        return '%s. %s(%d)' % (self.title, self.writer, self.readcount)
    
    def incrementReadCount(self):
        self.readcount += 1
        self.save()

board/views.py
from django.shortcuts import render, redirect, reverse
from .models import Board


def remove(request, id):
    board = Board.objects.get(pk=id)
    if request.method == 'POST':
        board.delete()
        return redirect(reverse('board:list'))
    else:
        return render(request, 'board/remove.html', {'board':board})

def edit(request):
    board = Board.objects.get(pk=id)
    if request.method == 'POST':
        board.title = request.POST['title']
        board.writer = request.POST.get('writer')
        board.content = request.POST['content']
        board.save()
        return redirect(reverse('board:read', args=(id,)))
    else:
        return render(request, 'board/edit.html', {'board':board})

def regist(request):
    if request.method == 'POST':
        title = request.POST['title']
        writer = request.POST.get('writer')
        content = request.POST['content']
        Board(title=title, writer=writer, content=content).save()
        return redirect(reverse('board:list'))
    else:
        return render(request, 'board/regist.html')
    
def read(request, id):
    board = Board.objects.get(pk=id)
    board.incrementReadCount()
    return render(request, 'board/read.html', {'board': board})

def list(request):
    board_list = Board.object.all().order_by('-id')
    context = {
        'board_list': board_list,
    }
    return render(
        request, 
        'board/list.html', 
        context
        )

def index(request):
    return render(request, 'board/index.html')

board/templates/board/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

board/templates/board/edit.html
<!-- 생략 -->

board/templates/board/index.html
{% extneds 'board/base.html' %}
{% title %}Index{% endblock %}
{% block content %}
<ul>
    <li><a href="{% url 'board:list' %}">목록</a></li>4
    <li><a href="#">등록</a></li>
</ul>
{% endblock %}

board/templates/board/list.html
{% extneds 'board/base.html' %}
{% block title %}목록록{% endblock %}
{% block content %}
{% if board_list %}
    <table border="1">
        <tr>
            <th>번호</th>
            <th>제목</th>
            <th>작성자</th>
            <th>조회수</th>
        </tr>
    {% for board in board_list %}
        <tr>
            <td>{{board.Index}}</td>
            <td><a href="{% url 'board:read' board.id %}">{{board.title}}</a></td>
            <td>{{board.writer}}</td>
            <td>{{board.readcount}}</td>
        </tr>
    {% endfor %}
    </table>
{% else %}
    게시글이 존재하지 않습니다.
{% endif %}
<a href="#"><button>등록</button></a>
{% endblock %}

board/templates/board/read.html
{% extneds 'board/base.html' %}
{% block title %}내용{% endblock %}
{% block content %}

<table border="1">
    <tr>
        <th>등롣일</th>
        <th>조회수</th>
    </tr>
    <tr>
        <td>{{board.regdate}}</td>
        <td>{{board.readcount}}</td>
    </tr>
    <tr>
        <td>제목</td>
        <td>{{board.title}}</td>
    </tr>
</table>
<a href="{% url 'board:edit' board.id %}"></a><button>수정</button></a>
<a href="{% url 'board:remove' board.id %}"><button>삭제</button></a>
<a href="{% url 'board:list' %}"><button>목록</button></a>
{% endblock %}

board/templates/board/regist.html
<!-- 생략 -->

board/templates/board/remove.html
<!-- 생략 -->